# Generated by Django 3.2.5 on 2021-08-15 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='profiles.images/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='media_url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
