# Generated by Django 3.2.5 on 2021-08-16 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='profiles.images/default_ava.png', null=True, upload_to='profiles.images/'),
        ),
    ]
