# Generated by Django 3.2.5 on 2021-07-30 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('views', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(upload_to='blogs.images')),
            ],
        ),
    ]
