# Generated by Django 3.2.5 on 2021-07-30 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blogs',
            new_name='Post',
        ),
    ]
