# Generated by Django 3.2.5 on 2021-08-14 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_comments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
